ALTER TABLE ORDERS
ADD CONSTRAINT fk_orders_user
FOREIGN KEY (USERID) REFERENCES USERBASE(USERID);

ALTER TABLE REVIEWS
ADD CONSTRAINT fk_reviews_user
FOREIGN KEY (USERID) REFERENCES USERBASE(USERID);

ALTER TABLE USERLIBRARY
ADD CONSTRAINT fk_userlibrary_user
FOREIGN KEY (USERID) REFERENCES USERBASE(USERID);


SELECT 
    CONCAT(FIRSTNAME, ' ', LASTNAME) AS FullName,
    USERNAME
FROM USERBASE
WHERE DATEDIFF(YEAR, DATEOFBIRTH, GETDATE()) >= 18;

SELECT 
    MAX(LEN(USERNAME)) AS MaxUsernameLength,
    AVG(CAST(LEN(USERNAME) AS DECIMAL(10,2))) AS AvgUsernameLength
FROM USERBASE;

SELECT QUESTION
FROM SECURITYQUESTION
WHERE QUESTION LIKE 'What is%' OR QUESTION LIKE 'What was%';

SELECT 
    PRODUCTCODE,
    MIN(RATING) AS LowestRating,
    COUNT(*) AS ReviewCount
FROM REVIEWS
GROUP BY PRODUCTCODE
ORDER BY ReviewCount DESC;

SELECT 
    PRODUCTCODE,
    COUNT(*) AS NumberOfUsers
FROM WISHLIST
WHERE POSITION = 1
GROUP BY PRODUCTCODE;

SELECT 
    USERID,
    SUM(PRICE) AS TotalSpent
FROM ORDERS
GROUP BY USERID;

SELECT 
    PURCHASEDATE,
    SUM(PRICE) AS GrossProfit
FROM ORDERS
GROUP BY PURCHASEDATE
ORDER BY GrossProfit DESC;

SELECT 
    PRODUCTCODE,
    SUM(HOURSPLAYED) AS TotalHoursPlayed
FROM USERLIBRARY
GROUP BY PRODUCTCODE
ORDER BY TotalHoursPlayed DESC
FETCH FIRST 5 ROWS ONLY;

CREATE VIEW UserInfractionCount AS
SELECT 
    USERID,
    COUNT(*) AS InfractionCount
FROM INFRACTIONS
GROUP BY USERID;

CREATE VIEW UserRuleInfractions AS
SELECT 
    USERID,
    RULENUM,
    COUNT(*) AS TimesBroken
FROM INFRACTIONS
GROUP BY USERID, RULENUM;

SELECT 
    i.RULENUM,
    i.PENALTY,
    COUNT(*) AS TimesAssigned
FROM INFRACTIONS i
WHERE i.PENALTY IS NOT NULL
GROUP BY i.RULENUM, i.PENALTY;

SELECT 
    AVG(DATEDIFF(DAY, DATESUBMITTED, DATEUPDATED)) AS AvgDaysToClose,
    MAX(DATEDIFF(DAY, DATESUBMITTED, DATEUPDATED)) AS MaxDaysToClose,
    MIN(DATEDIFF(DAY, DATESUBMITTED, DATEUPDATED)) AS MinDaysToClose
FROM TICKETS
WHERE STATUS = 'CLOSED';

SELECT 
    t.EMAIL,
    t.ISSUE,
    COUNT(*) AS IssueCount
FROM TICKETS t
WHERE t.STATUS = 'NEW'
GROUP BY t.DATESUBMITTED, t.EMAIL, t.ISSUE
ORDER BY IssueCount;

SELECT 
    USERID,
    USERNAME,
    FIRSTNAME,
    LASTNAME,
    PASSWORD
FROM USERBASE
WHERE PASSWORD LIKE '%' || FIRSTNAME || '%' 
   OR PASSWORD LIKE '%' || LASTNAME || '%';


SELECT 
    PUBLISHER,
    AVG(PRICE) AS AveragePrice
FROM PRODUCT
GROUP BY PUBLISHER
ORDER BY PUBLISHER;

CREATE VIEW OldProductsWithDiscount AS
SELECT 
    PRODUCTNAME,
    PRICE * 0.75 AS DiscountedPrice
FROM PRODUCT
WHERE MONTHS_BETWEEN(SYSDATE, RELEASEDATE) / 12 > 5;

SELECT 
    GENRE,
    MAX(PRICE) AS MaxPrice,
    MIN(PRICE) AS MinPrice
FROM PRODUCT
GROUP BY GENRE;

CREATE VIEW RecentChatLog AS
SELECT *
FROM CHATLOG
WHERE DATESENT >= SYSDATE - 7;

CREATE VIEW RecentInfractions AS
SELECT 
    USERID,
    DATEASSIGNED,
    PENALTY
FROM INFRACTIONS
WHERE PENALTY IS NOT NULL 
  AND DATEASSIGNED >= ADD_MONTHS(SYSDATE, -1);
