SELECT u.USERNAME, MIN(r.RATING) AS LowestRating
FROM USERBASE u
LEFT JOIN REVIEWS r ON u.USERID = r.USERID
GROUP BY u.USERNAME, u.USERID
ORDER BY LowestRating;

SELECT u.FIRSTNAME, u.EMAIL, u.WALLETFUNDS
FROM USERBASE u
LEFT JOIN WISHLIST w ON u.USERID = w.USERID
WHERE w.USERID IS NULL;

SELECT u.USERNAME, COUNT(o.ORDERID) AS NumberOfOrders
FROM USERBASE u
LEFT JOIN ORDERS o ON u.USERID = o.USERID
GROUP BY u.USERNAME, u.USERID
ORDER BY NumberOfOrders DESC;

SELECT DISTINCT p.PRODUCTNAME, p.RELEASEDATE, p.PRICE, p.DESCRIPTION
FROM PRODUCTLIST p
INNER JOIN WISHLIST w ON p.PRODUCTCODE = w.PRODUCTCODE
ORDER BY p.RELEASEDATE;

SELECT p.PRODUCTNAME, 
       MAX(r.RATING) AS HighestRating, 
       COUNT(r.REVIEW) AS NumberOfReviews
FROM PRODUCTLIST p
INNER JOIN REVIEWS r ON p.PRODUCTCODE = r.PRODUCTCODE
GROUP BY p.PRODUCTCODE, p.PRODUCTCODE
ORDER BY HighestRating DESC;

SELECT p.GENRE, COUNT(o.PRODUCTCODE) AS ProductsOrderedCount
FROM PRODUCTLIST p
LEFT JOIN ORDERS o ON p.PRODUCTCODE = o.PRODUCTCODE
GROUP BY p.GENRE
ORDER BY p.GENRE;

CREATE VIEW ProductRatingSummary AS
SELECT p.PRODUCTNAME, p.GENRE, r.RATING
FROM PRODUPRODUCTLISTCTS p
INNER JOIN REVIEWS r ON p.PRODUCTCODE = r.PRODUCTCODE
WHERE r.RATING IN (5, 1)
ORDER BY r.RATING ASC;

SELECT p.GENRE, COUNT(o.PRODUCTCODE) AS ProductsOrderedCount
FROM PRODUCTLIST p
LEFT JOIN ORDERS o ON p.PRODUCTCODE = o.PRODUCTCODE
GROUP BY p.GENRE
ORDER BY p.GENRE;   


CREATE VIEW PublisherStats AS
SELECT p.PUBLISHER, 
       AVG(p.PRICE) AS AveragePrice, 
       SUM(ul.HOURSPLAYED) AS TotalHoursPlayed
FROM PRODUCTLIST p
LEFT JOIN USERLIBRARY ul ON p.PRODUCTCODE = ul.PRODUCTCODE
GROUP BY p.PUBLISHER;

SELECT p.PUBLISHER, SUM(o.PRICE) AS TotalMoneySpent
FROM ORDERS o
INNER JOIN PRODUCTLIST p ON o.PRODUCTCODE = p.PRODUCTCODE
GROUP BY p.PUBLISHER
ORDER BY TotalMoneySpent DESC;
