SELECT USERID FROM USERBASE
MINUS
SELECT USERID FROM ORDERS;

SELECT PRODUCTCODE FROM PRODUCTLIST
MINUS
SELECT PRODUCTCODE FROM REVIEWS;

SELECT ub.*,
       CASE 
           WHEN (SYSDATE - BIRTHDAY)/365 >= 18 THEN 'Adult'
           ELSE 'Minor'
       END AS AGE_CATEGORY
FROM USERBASE ub;

SELECT pl.*,
       CASE 
           WHEN PRICE <= 20 THEN 'On Sale'
           ELSE 'Base Price'
       END AS PRICE_CATEGORY
FROM PRODUCTLIST pl;

SELECT USERID FROM USERPROFILE 
WHERE IMAGEFILE IS NOT NULL
INTERSECT
SELECT USERID FROM USERLIBRARY 
WHERE PRODUCTCODE = 'GAME6';

SELECT u1.USERNAME AS USERNAME1, u2.USERNAME AS USERNAME2, u1.BIRTHDAY
FROM USERBASE u1
JOIN USERBASE u2 ON u1.BIRTHDAY = u2.BIRTHDAY AND u1.USERID < u2.USERID;

SELECT * FROM USERLIBRARY
CROSS JOIN WISHLIST;


SELECT 'USER' AS RECORD_TYPE, USERID AS ID, USERNAME AS NAME, EMAIL, BIRTHDAY, NULL AS PRICE, NULL AS PRODUCTCODE
FROM USERBASE
UNION ALL
SELECT 'PRODUCT' AS RECORD_TYPE, NULL AS ID, NULL AS NAME, NULL AS EMAIL, NULL AS BIRTHDAY, PRICE, PRODUCTCODE
FROM PRODUCTLIST;

SELECT 'CHAT' AS ACTIVITY_TYPE, USERID, TIMESTAMP AS ACTIVITY_DATE, MESSAGE AS ACTIVITY_DETAIL
FROM CHATLOG
UNION ALL
SELECT 'PROFILE' AS ACTIVITY_TYPE, USERID, LASTUPDATED AS ACTIVITY_DATE, PROFILEIMAGE AS ACTIVITY_DETAIL
FROM USERPROFILE;


SELECT CHATID AS ACTIVITY_DATE, CONTENT  AS ACTIVITY_DETAIL
FROM CHATLOG
UNION ALL
SELECT  USERID,  DESCRIPTION AS ACTIVITY_DETAIL
FROM USERPROFILE;


SELECT USERNAME FROM USERBASE
WHERE USERID NOT IN (SELECT USERID FROM INFRACTIONS);

SELECT TITLE, DESCRIPTION FROM COMMUNITYRULES
WHERE RULENUM NOT IN (SELECT RULENUM FROM INFRACTIONS);


SELECT u.USERNAME, u.EMAIL
FROM USERBASE u
JOIN INFRACTIONS i ON u.USERID = i.USERID
WHERE i.PENALTY IS NOT NULL;




SELECT i.DATEASSIGNED AS INFRACTION_DATE
FROM INFRACTIONS i
INTERSECT
SELECT us.DATESUBMITTED AS SUPPORT_DATE
FROM USERSUPPORT us;






SELECT cr.TITLE, i.PENALTY
FROM COMMUNITYRULES cr
LEFT JOIN INFRACTIONS i ON cr.RULENUM = i.RULENUM;

SELECT cr.*,
       CASE 
           WHEN SEVERITYPOINT >= 10 THEN 'Bannable'
           ELSE 'Appealable'
       END AS RULE_SEVERITY
FROM COMMUNITYRULES cr;

SELECT us.*,
       CASE 
           WHEN STATUS != 'CLOSED' AND DATEUPDATED < SYSDATE - 7 THEN 'High Priority'
           ELSE 'Normal Priority'
       END AS PRIORITY_STATUS
FROM USERSUPPORT us;

SELECT * FROM USERSUPPORT
CROSS JOIN INFRACTIONS;

SELECT us1.TICKETID, us1.DATEUPDATED
FROM USERSUPPORT us1
JOIN USERSUPPORT us2 ON us1.TICKETID = us2.TICKETID
WHERE us1.STATUS = 'CLOSED' 
  AND us2.STATUS = 'CLOSED'
  AND us1.DATEUPDATED = us2.DATEUPDATED
  AND us1.ROWID != us2.ROWID;



SELECT 'USER_INFO' AS DATA_TYPE, USERID, USERNAME AS NAME_OR_REASON, EMAIL AS ADDITIONAL_INFO, BIRTHDAY AS DATE_INFO
FROM USERBASE
UNION ALL
SELECT 'INFRACTION' AS DATA_TYPE, USERID, PENALTY AS NAME_OR_REASON, TO_CHAR(PENALTY) AS ADDITIONAL_INFO, DATEASSIGNED AS DATE_INFO
FROM INFRACTIONS;
