--Tevin Donegan

-- 1
SELECT USER_ID, USERNAME, CREATED, PASSWORD_CHANGE_DATE 
FROM USER_USERS;

-- 2
SELECT * FROM USER_TABLES;

-- 3
DESCRIBE ORDERS;
DESCRIBE PRODUCTLIST;
DESCRIBE REVIEWS;
DESCRIBE STOREFRONT;
DESCRIBE USERBASE;
DESCRIBE USERLIBRARY;

-- 4
SELECT * FROM ORDERS;
SELECT * FROM PRODUCTLIST;
SELECT * FROM REVIEWS;
SELECT * FROM STOREFRONT;
SELECT * FROM USERBASE;
SELECT * FROM USERLIBRARY;

-- 5
SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS 
FROM USER_CONSTRAINTS;

-- 6
SELECT VIEW_NAME, TEXT 
FROM USER_VIEWS;

-- 7
SELECT USERNAME 
FROM USERBASE 
ORDER BY USERNAME;

-- 8
SELECT FIRSTNAME, LASTNAME, USERNAME, PASSWORD, EMAIL 
FROM USERBASE 
WHERE EMAIL LIKE '%yahoo.com' 
   OR EMAIL LIKE '%yahoo.co.uk' 
   OR EMAIL LIKE '%yahoo.%';

-- 9
SELECT USERNAME, BIRTHDAY, WALLETFUNDS 
FROM USERBASE 
WHERE WALLETFUNDS < 25;

-- 10
SELECT USERID, PRODUCTCODE 
FROM USERLIBRARY 
WHERE HOURSPLAYED > 100;

-- 11
SELECT PRODUCTCODE 
FROM USERLIBRARY 
WHERE HOURSPLAYED < 10;

-- 12
SELECT DISTINCT PUBLISHER 
FROM PRODUCTLIST;

-- 13
SELECT PRODUCTNAME, RELEASEDATE, PUBLISHER, GENRE 
FROM PRODUCTLIST 
ORDER BY GENRE;

-- 14
SELECT PRODUCTCODE, PUBLISHER 
FROM PRODUCTLIST 
WHERE GENRE = 'Strategy';

-- 15
SELECT PRODUCTCODE, DESCRIPTION, PRICE 
FROM PRODUCTLIST 
WHERE PRICE > 25 
ORDER BY PRICE DESC;

-- 16
SELECT INVENTORYID, PRICE 
FROM STOREFRONT 
ORDER BY PRICE ASC;

-- 17
SELECT PRODUCTCODE, REVIEW 
FROM REVIEWS 
WHERE RATING = 1;

-- 18
SELECT PRODUCTCODE, REVIEW 
FROM REVIEWS 
WHERE RATING >= 4;

-- 19
SELECT DISTINCT USERID 
FROM ORDERS;

-- 20
SELECT * 
FROM ORDERS 
ORDER BY PURCHASEDATE ASC;
